### ISSUE TITLE
Folder convert NDF to H5 does not yield files

### ISSUE THREAD

**Issue by raubsau** [jcornford/pyecog#12]
When executing
```
handler.convert_ndf_directory_to_h5(ndf_dir = '/absolute/path'
                                    , tids = '11'
                                    , fs = 512
                                    # , n_cores = -1
                                    , save_dir = '/absolute/path'
                                    )
```
the correct number of files is found, one file seems to get converted but is not saved anywhere. After one file it stops.
With setting `tids = 'all'` conversion is working fine, but chosing a specific channel seems to break something.

**Comment by jcornford** [comment]
Hi, this sounds like it could be the specific channel you have entered is not valid for your files? I agree having it fail silently is not ideal.

If you look at the .log file that should be automatically made in the working directory you will see a line like
```
INFO - Valid ids and freq are: {1: 512, 2: 512, 3: 512, 4: 512, 5: 512, 7: 512, 8: 512, 9: 512, 11: 512, 13: 512, 14: 512}
2017-03-15 13:53:39,345 - WARNING - Not all read tids:[22] were valid for M1473321440.ndf skipping!
```
if the tid is not valid. If you check the tids at the end of a converted h5 file, which will look something like "M1473307040_2016-09-08_04_57_20 tids_[1, 2, 7, 8, 9, 11, 13, 14].h5" on the most recent version, you can also double check you have the right id?

Also, note, currently (temporarily) if you have the n_cores set to anything but 1, the file order can come out slightly jumbled  - which can be annoying for using the gui to visualise them.

**Comment by raubsau** [comment]
Using channel 12:

```2017-03-15 15:36:58,618 - INFO - Valid ids and freq are: {3: 512.0, 12: 512.0, 13: 512.0, 7: 512.0}
2017-03-15 15:36:58,618 - WARNING - Not all read tids:12 were valid for M1412342952.ndf skipping!
2017-03-15 15:36:58,618 - WARNING - Not all read tids:12 were valid for M1412342952.ndf skipping!```

**Comment by raubsau** [comment]
Using channel 12 and commenting n_cores out:
```
2017-03-15 15:36:58,618 - INFO - Valid ids and freq are: {3: 512.0, 12: 512.0, 13: 512.0, 7: 512.0}
2017-03-15 15:36:58,618 - WARNING - Not all read tids:12 were valid for M11234567890.ndf skipping!
2017-03-15 15:36:58,618 - WARNING - Not all read tids:12 were valid for M1234567890.ndf skipping!
```

**Comment by jcornford** [comment]
By commenting n_cores out you'll just be passing the default argument, which is -1, so I'd set it to 1.

Strange that the log is saying that tid 12 is valid, but then doesn't load/convert it.  Do the other tids produce files? Will look into the valid tid generation/warning generation.

**Comment by raubsau** [comment]
No, setting other tids does not help. Also putting only ndfs in a folder does not help.

**Comment by jcornford** [comment]
Ahh, convert_ndf_directory_to_h5 is currently expecting either the string 'all', and integer id, or a list of integer ids. Sorry, this wasn't explicit in the function info. 

I'll update the code to handle this. Meanwhile, to verify passing a string was the problem, passing either
```python
tids = 11
```
or
```python
[3,12,7]
```
should work?

**Comment by raubsau** [comment]
Yes giving
```tids = 11
```
works as expected. Thank you 👍

**Comment by jcornford** [comment]
Great. I changed the code so it now should handle a string if it gets one. Also, using more than one core should also maintain the date modified timestamp order in your directory. (v.1.42).
