### ISSUE TITLE
Scrolling through transmitter IDs only works with up button

### ISSUE THREAD

**Issue by mikailweston** [jcornford/pyecog#25]
Scrolling through Tids in a h5 file increments upwards correctly

Pressing the down button does not work as expected if there is no Tid directly preceeding the current one.

e.g. 1--> 2 --> 3 --> 4 --> 3 -->4 --> 7 -/-> 4
                                                                --> 8

**Comment by jcornford** [comment]
don't understand what is wrong with the down button, could you explain in more detail?

**Comment by mikailweston** [comment]
Down button does not work if the next lowest Tid is not consecutive to the current. 
eg:

2-->1 works
3-->1 does not work

**Comment by jcornford** [comment]
can you put example file in documentation notebooks

**Comment by jcornford** [comment]
fixed
