### ISSUE TITLE
Create new folder if none exists

### ISSUE THREAD

**Issue by mikailweston** [jcornford/pyecog#29]
If a folder name does not exist, create it. 
To be used anywhere there a select folder dialog window started

**Comment by jcornford** [comment]
dont understand - on mac when you have the window for select folder  you have the new folder icon in bottom left

![screen shot 2017-07-22 at 15 02 30](https://user-images.githubusercontent.com/8012514/28491796-eea9d7ee-6eee-11e7-935b-7a4052b88a4f.png)

**Comment by jcornford** [comment]
closing as not needed - windows has the same functionality
