### ISSUE TITLE
Easy way to start pyecog

### ISSUE THREAD

**Issue by mikailweston** [jcornford/pyecog#7]
**There is no easy way to start pyecog.**

For example, typing "`pyecog`" in the terminal once pyecog is installed with pip should start the main GUI

**Comment by jcornford** [comment]
Yes, I agree this is suboptimal. Will look into this.

**Comment by jcornford** [comment]
Okay, I added a main_gui.py in the pyecog folder. This calls the gui in the visualisation folder. 

I've also changed the imports so it works without requiring pyecog to be installed as a module.

Will close this issue once you have tested: 

```
python pyecog/main_gui.py
```
Hope it works!

**Comment by mikailweston** [comment]
Thanks, any chance you can push it to pip?

**Comment by jcornford** [comment]
Assuming it works then. Yes, will do Monday

**Comment by jcornford** [comment]
This is no longer the way to run the gui:

```python
import pyecog
pyecog.pyecog_main_gui.main()
```

**Comment by mikailweston** [comment]
Added entry point "pyecog" to be run after environment activated. See run instructions
